### ISSUE TITLE
Change labels for "my events" to be consistent

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/tlpd#170] opened 2019-02-13 18:57 UTC
### Description 

There are inconsistent labels used to describe the My Events page

**Expected behaviour** 

All links to the My Events page should use a consistent label.

- Update the link in the user/logout drop down to say "My Events" rather than "myTLPD"
![screen shot 2019-02-13 at 11 18 43 am](https://user-images.githubusercontent.com/43043264/52737503-5b444c00-2f81-11e9-9f0a-0f6694fad9be.png)

- Update the link in the main menu bar to standard styling (i.e., remove italics on "MY")

![screen shot 2019-02-13 at 11 18 50 am](https://user-images.githubusercontent.com/43043264/52737524-6a2afe80-2f81-11e9-893c-2ff98de1684e.png)

**Actual behaviour** 

There are inconsistent labels used to describe the My Events page

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by bdolor** [comment] 2019-02-13 19:06
@dshaykewich there are fields in the issue template that help us to identify where the issue is. For instance, in the 'steps to reproduce the problem' you could provide links to the various pages where you see the inconsistencies. Screen shots are another option.

**Comment by dshaykewich** [comment] 2019-02-13 19:22
Thanks @bdolor .  I was creating the issues on the fly in the meeting and am now coming back to fill them out.

**Comment by bdolor** [comment] 2019-02-13 19:28
empty templates makes for unhappy developers. thanks Dave.

**Comment by paulagaube** [comment] 2019-02-13 21:23
@bdolor You are a keener! Dave, @kkilbey and I met this morning to go over outstanding TLPD issues and are still fleshing out a couple of these tickets. It is a good reminder to not forget the details! 
And @dshaykewich I see you split the "Maintenance" Label in to three: Perfective, Adaptive, and Corrective. This makes me smile. Especially "Perfective Maintenance" :)

**Comment by bdolor** [comment] 2019-02-13 21:32
Thanks for grooming the list Paula and Kelsey...I changed the labels to better reflect the categories of maintenance activities seen in SD. ref: http://swebokwiki.org/Chapter_5:_Software_Maintenance#Categories_of_Maintenance

**Comment by paulagaube** [comment] 2019-02-13 21:38
Oh, @bdolor that was you who changed the labels! Ok, thanks for being corrective and perfective! I also like "preventative maintenance"! I think Kelsey and I are going to use those tag in the support repository too. :) Or at least the perfective one.

**Comment by bdolor** [comment] 2019-02-13 21:39
keener is as keener does... :nerd_face:

**Comment by alex-418** [comment] 2019-02-19 19:53
Completed via https://github.com/BCcampus/tlpd/commit/6af022f6899454d4b669b3563daffe417d424b76

**Comment by kkilbey** [comment] 2019-02-19 23:32
@alex-418 Looks good in the top corner drop-down!

Could you please also un-italicize the "My" in the top bar menu? (Visible only to logged-in users.)
![image](https://user-images.githubusercontent.com/44710357/53055030-2f323a80-345b-11e9-929f-542a8789027b.png)

**Comment by alex-418** [comment] 2019-02-20 01:29
No problem @kkilbey i've now removed italics on the "My" via https://github.com/BCcampus/tlpd/commit/17c4ddabb587e7fa13e17e42242671dbc4ceeac8

**Comment by kkilbey** [comment] 2019-02-20 16:43
Thanks @alex-418 ! Moving this to "Done."

**Closed** 2019-02-21 17:43 UTC
Labels: Perfective Maintenance, small-1
