### ISSUE TITLE
Profile form for Contributor: Content change

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/tlpd#58] opened 2018-09-11 21:56 UTC
### Description 

In the account profile for  Contributor change the order Institution first then and OR for Organization or Agency. Majority of people are from a post-sec institution

**Expected behaviour** 

[What you expect/want to happen]

**Actual behaviour** 

[What actually happened]

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by bdolor** [comment] 2018-09-24 21:08
if this is the 'sign up' form, then it's a non-dev task. Form fields for registration are in Users->Profile Fields and come with drag/drop functionality to switch the order.

**Comment by jgrajkowski** [comment] 2018-09-27 21:49
Review yesterday with Leva and Paula.
Changed this form on PROD to provide a required institution or enter something in next Other.  

Unassigning self in the hope someone can confirm https://tlpd.bccampus.ca/sign-up/ order and content makes sense.

**Comment by BCcLeva** [comment] 2018-09-28 19:15
I've checked on DEV and Prod the order of the fields for signup form and they are in the correct order.

**Comment by BCcLeva** [comment] 2018-09-28 19:29
![screen shot 2018-09-28 at 12 29 28 pm](https://user-images.githubusercontent.com/34721375/46229339-2dd06c00-c31a-11e8-8b61-ebda672dce9f.png)

**Comment by jgrajkowski** [comment] 2018-09-28 20:53
I think the above screenshot was intended to go with #121 :)

Signup field order, field type, and titles seem good and to display well on Win Chrome and FFF. Moving to done.

**Closed** 2018-09-28 22:39 UTC
Labels: non-dev, small-1
